# Generated by Django 5.2.3 on 2025-07-01 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_kundlidetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZodiacSign',
        ),
    ]
