# Generated by Django 5.2.3 on 2025-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0005_kundlidetails_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundlidetails',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
