# Generated by Django 5.2.3 on 2025-07-01 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0003_delete_zodiacsign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kundlidetails',
            options={'verbose_name_plural': 'Kundli Details'},
        ),
    ]
