# Generated by Django 5.2.3 on 2025-07-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0004_alter_kundlidetails_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='kundlidetails',
            name='timezone',
            field=models.CharField(choices=[('Asia/Kolkata', 'Asia/Kolkata'), ('UTC', 'UTC'), ('America/New_York', 'America/New_York'), ('Europe/London', 'Europe/London')], default='Asia/Kolkata', help_text='Select the time zone of the place of birth.', max_length=50),
        ),
    ]
